buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Android Gradle Plugin，用于 android 模块构建 APK
        classpath 'com.android.tools.build:gradle:8.2.0'
    }
}

allprojects {
    version = '1.0'
    ext {
        appName = 'RacingGame'
        gdxVersion = '1.12.1'
    }
    repositories {
        google()
        mavenCentral()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
        maven { url 'https://s01.oss.sonatype.org/content/repositories/snapshots/' }
        maven { url 'https://jitpack.io' }
    }
}
